### PR TITLE
US12_Veronika

### PR DESCRIPTION
**Pull request by VeronikaKrasnokutska**
VYT_US12

### CODE REVIEW

**Review by AnnaLoshak — APPROVED** [review]
Good job!

**Review by ZaierAouani — APPROVED** [review]
Great work. Thanks!

**Review by BadamkhandB — APPROVED** [review]
Great job

**Review by tsjuder1 — APPROVED** [review]
Beautiful

**Review by natebell510 — APPROVED** [review]
nice

**Pull request merged**
